---
version: 0.0
os: linux
files:
  - source: /index.html
  - source: /globo_logo.png 
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: /stop_server.sh
      timeout: 300
      runas: root
    - location: /before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start_server.sh
      timeout: 300
      runas: root
