---
version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
    - source: /globo_logo.png 
    destination: /opt/codedeploy-agent/deployment-root/e98d332c-7494-48ea-9f79-738cdf07c985/d-NKS6Q7163/deployment-archive

hooks:
  BeforeInstall:
    - location: /stop_server.sh
      timeout: 300
      runas: root
    - location: /before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start_server.sh
      timeout: 300
      runas: root
